### ISSUE TITLE
Smartsheet API integration request

### ISSUE THREAD

**Issue by Frenchcooc** [Bearer/Pizzly#102]
In october, Pizzly teams up with Hacktoberfest 2020 to increase the number of API integrations to up to 100 APIs 🎉 To learn more about how to participate and win, look at [our Hacktoberfest guide](https://github.com/Bearer/Pizzly/blob/master/HACKTOBERFEST.md).

**Smartsheet** has been identified as a major API that we would love to support. Your mission is to create a configuration file that make this API ready to be used by Pizzly developers.

Here are a few links to help you achieve this task:

* [Smartsheet official website](https://www.smartsheet.com/)
* [Smartsheet Developers Portal](https://smartsheet-platform.github.io/)
* [Smartsheet's OAuth documentation](https://smartsheet-platform.github.io/api-docs/#third-party-app-development)
* [Pizzly's guide on how to add a new integration](https://github.com/Bearer/Pizzly/wiki/Reference-:-Integrations#adding-a-new-integration)

If you are interested in adding this integration to Pizzly, please comment below first, to tell other contributors that you're on it. 

Once you've the configuration ready, please create a PR that links to this issue ([more detail in our Hacktoberfest guide](https://github.com/Bearer/Pizzly/blob/master/HACKTOBERFEST.md)).

Happy hacking! 👨‍🎤

**Comment by saikirankv** [comment]
@Frenchcooc I created a PR, can you review?
