### ISSUE TITLE
Add "Hacktoberfest" to topics

### ISSUE THREAD

**Issue by TheNoim** [Bearer/Pizzly#121]
Hacktoberfest PR's will be invalid if this repo doesn't have the Hacktoberfest topic:

![Screen Shot 2020-10-03 at 14 29 06](https://user-images.githubusercontent.com/5133056/94991672-ce4e6c00-0584-11eb-87ea-2714bdcd8be2.png)

**Comment by Frenchcooc** [comment]
Thanks a lot for reporting this. Will be updated ASAP.

**Comment by Frenchcooc** [comment]
Can you double check and confirm it's ok now?

**Comment by TheNoim** [comment]
Yes, it is.
