### ISSUE TITLE
Soundcloud API integration request

### ISSUE THREAD

**Issue by listopadiya** [Bearer/Pizzly#126]
As **Soundcloud** supports OAUTH authentication and provides nice API options to developers, would be good to add it into Pizzly.

Here are a few links to help you achieve this task:

* [Soundcloud official website](https://soundcloud.com/)
* [Soundcloud Developers Portal](https://developers.soundcloud.com/)
* [Soundcloud's API Reference](https://developers.soundcloud.com/docs/api/reference)
* [Soundcloud's OAuth documentation](https://developers.soundcloud.com/docs/api/guide#authentication)
* [Pizzly's guide on how to add a new integration](https://github.com/Bearer/Pizzly/wiki/Reference-:-Integrations#adding-a-new-integration)

**Comment by NimperX** [comment]
May I work on this @listopadiya 😎
