### ISSUE TITLE
Jira configuration undefined variable headers.atlassian_domain

### ISSUE THREAD

**Issue by richardkyk** [Bearer/Pizzly#131]
I'm trying to call the Jira endpoint "/search"  from the dashboard but I'm getting the error down below.

error:Object
type:"invalid_proxy_configuration_interpolation"
message:"Proxy configuration template interpolation error: Undefined variable headers.atlassian_domain used in template at "

I am able to get an Auth ID, and if I inspect it I can see the accessToken, which I have also verified that it works in Postman so the process for authenticating is all good. But when I am testing the request it doesn't seem to work.

Also, is there anyway to change the base URL? According to the Jira documentation, "Requests that use OAuth 2.0 (3LO) are made via api.atlassian.com (not https://your-domain.atlassian.net)."

**Comment by Frenchcooc** [comment]
@richardkyk Jira configuration file has been updated with this PR https://github.com/Bearer/Pizzly/pull/136. Can you update the Pizzly version you are using by pulling master?

**Comment by richardkyk** [comment]
@Frenchcooc Perhaps "/ex/"  should not be included in the baseURL as you need to reach the "https://api.atlassian.com/oauth/token/accessible-resources" endpoint to get the cloudId before you can call the "https://api.atlassian.com/ex/jira/(cloud_id)/rest/api/2/project" endpoint.

**Comment by Frenchcooc** [comment]
@richardkyk I'm not sure what are the best options here. What do you recon?

**Comment by Frenchcooc** [comment]
Closing this issue for now. Feel free to reopen it if needed.
