### ISSUE TITLE
sevDesk integration

### ISSUE THREAD

**Issue by lukas-mertens** [Bearer/Pizzly#137]
I would like to add a sevDesk integration during Hacktoberfest, if that's okay. sevDesk is a cloud-accounting software, I use a lot so an integration would be very useful for me and most likely for many other users as well.

**Comment by Frenchcooc** [comment]
Hi @lukas-mertens. Sure that would be really great! Feel free to create a PR and we will review it + make it count towards Hacktoberfest.

**Comment by Frenchcooc** [comment]
@lukas-mertens are you still up to make a sevDesk integration?

**Comment by lukas-mertens** [comment]
Hey, yes I am. I just didn't get to it yet. I hope I am going to be able
to do it during this week

**Comment by lukas-mertens** [comment]
Actually the new sevDesk-API isn't released yet and the old one doesn't use OAuth, so this issue doesn't make any sense ^^ I will work on another integration instead ;)
