### ISSUE TITLE
Vimeo API integration request

### ISSUE THREAD

**Issue by listopadiya** [Bearer/Pizzly#141]
As **Vimeo** supports OAUTH authentication and provides nice API options to developers, would be good to add it into Pizzly.

Here are a few links to help you achieve this task:

* [Vimeo official website](https://vimeo.com/)
* [Vimeo Developers Portal](https://developer.vimeo.com/)
* [Vimeo's OAuth documentation](https://developer.vimeo.com/api/authentication#obtaining-an-access-token)
* [Vimeo's API reference](https://developer.vimeo.com/api/reference)
* [Pizzly's guide on how to add a new integration](https://github.com/Bearer/Pizzly/wiki/Reference-:-Integrations#adding-a-new-integration)

**Comment by omnone** [comment]
Hey, i would like to give it a try . Thanks
