### ISSUE TITLE
Github configuration file does not contain header  to create a repository from template

### ISSUE THREAD

**Issue by zanio** [Bearer/Pizzly#146]
Hi, 
Thanks to the team developing the pizzly library.  I have an issue with the configuration file for GitHub in the integration folder.

I need to create a repository using an existing template, but according to the documentation of Github API, the request Header requires a different header: Please see the code below as copied from GitHub [create a repository from template api](https://docs.github.com/rest/reference/repos#create-a-repository-using-a-template)

```
curl \
  -X POST \
 H "Accept: application/vnd.github.baptiste-preview+json" \
  https://api.github.com/repos/TEMPLATE_OWNER/TEMPLATE_REPO/generate \
  -d '{"name":"name"}'
```

The Header `Accept: application/vnd.github.baptiste-preview+json` is not present in the configuration file of the pizzly project and many others accept media option.

Thanks

**Comment by markmichon** [comment]
Hey @zanio, if I'm understanding correctly you want to be able to add custom headers to specific requests? Pizzly lets you do this without changing the core config file. GitHub uses headers like that for certain features sometimes. The Pizzly wiki has a section on [adding your own header for specific requests](https://github.com/Bearer/Pizzly/wiki/Reference-:-Proxy#headers).

**Comment by zanio** [comment]
Thanks very much. Just seeing the docs. That page was hard to find

**Comment by Frenchcooc** [comment]
@zanio feel free to share where you were looking for at first and you didn't find the information. The docs are always a work in progress ;)
