### ISSUE TITLE
Document how to setup the local dev-environment with a postgres database

### ISSUE THREAD

**Issue by lukas-mertens** [Bearer/Pizzly#162]
Currently nowhere in the getting started-guide it is documented how to set the DB_PASSWORD and DB_USER for the database connection (they can be set as an environment variable). I was able to set it up by reverse engineering, but it would be nice if this was documented as well. I can't submit a PR to the Docs myself sadly, because GitHub doesn't support it, which is why I am creating this issue.

**Comment by Frenchcooc** [comment]
@lukas-mertens you're totally right! This was undocumented so far, by mistake. It has been fixed https://github.com/Bearer/Pizzly/wiki/Getting-started/_compare/e55ec0d945bb7398ad4857fe2244f800ac777d2e

**Comment by BjoernAkAManf** [comment]
You might also want to reference the docker-compose file, which is already provided. One only needs to specify a password using     ```environment:
       - POSTGRES_PASSWORD=melon
```

Not sure why that is not the default though 🤔

**Comment by Frenchcooc** [comment]
@BjoernAkAManf I'm more keen to let the `Getting Started` easy to follow - oriented toward new developers. docker-compose is already for advanced users to me.

But feel free to update/add comments in the `./docker-compose.yml` file.

**Comment by Frenchcooc** [comment]
Closing this issue. Feel free to reopen it if ever you feel it needs to.
