### ISSUE TITLE
Not able to refresh token via API

### ISSUE THREAD

**Issue by de-footspeed** [Bearer/Pizzly#173]
I have not had any success with refreshing a token via /api/:integration/authentications/:authId/refresh on my instance, so to verify I set up a fresh instance on Heroku, configured Github, connected and successfully ran a request.

Then I dropped into my command line and ran:
curl -X POST https://myapp.herokuapp.com/api/github/authentications/a93c9c80-1afa-11eb-8f4c-edc17efd9c4e/refresh 

The error message:
{"error":{"type":"token_refresh_failed","message":"Unable to refresh the token. Please re-connect that user."}}

This is the same error message I'm encountering on my other production instance. I also tested on a fresh localhost install and the error message is the same.

**Comment by Frenchcooc** [comment]
@de-footspeed thanks for reaching out. As far as I can tell, GitHub provides lifetime accessToken, thus you do not need to refresh it. That's why Pizzly is failing to refresh it. The error could be more explicit though.

**Comment by de-footspeed** [comment]
@Frenchcooc A more explicit error message would help with other custom integrations, of mine, that are failing as well. This would help me tweak my configuration files for the token refresh. I'll look at the code.

**Comment by Frenchcooc** [comment]
@de-footspeed I've made a better error message here: https://github.com/Bearer/Pizzly/pull/176

**Comment by Frenchcooc** [comment]
Closing this issue as the discussion has moved to #176
