### ISSUE TITLE
twitter integration

### ISSUE THREAD

**Issue by ishuacharis** [Bearer/Pizzly#175]
is there any reason why twitter oauth is not working after filling the correct credentials both on twitter app creation and on pizzly config setup

**Comment by Frenchcooc** [comment]
@ishuacharis this has been added with Twitter API v1 a few months ago. It should still work out!

**Comment by ishuacharis** [comment]
i get the error below when i click on sigin with twitter button on my application:

error:
message: "{&#34;statusCode&#34;:401,&#34;body&#34;:&#34;{&#34;errors&#34;:[{&#34;code&#34;:32,&#34;message&#34;:&#34;Could not authenticate you.&#34;}]}&#34;}"
type: "{&#34;statusCode&#34;:401,&#34;body&#34;:&#34;{&#34;errors&#34;:[{&#34;code&#34;:32,&#34;message&#34;:&#34;Could not authenticate you.&#34;}]}&#34;}"

**Comment by Frenchcooc** [comment]
Seems to work on my side. Without more information, I'm unable to reproduce the error unfortunately.

**Comment by ishuacharis** [comment]
this is the callback url i entered on twitter : https://prizzly-oauth-poll.herokuapp.com/auth/callback
website url: https://prizzly-oauth-poll.herokuapp.com
on pizzly config settings i entered my consumer secret and key
below is my connect function
 ` const conn  = () => {
  const prizzly = new Pizzly({
        host: "https://prizzly-oauth-poll.herokuapp.com"
      })
          const github =  prizzly.integration('twitter')
          github.connect()
          .then(connectionSuccess)
          .catch(connectionError)
        }`

**Comment by Frenchcooc** [comment]
Thanks. First, you should consider securing your instance ([how-to](https://github.com/Bearer/Pizzly/wiki/Secure-your-instance)). I'm able to retrieve a valid access token to GitHub by just opening your dashboard. This is unsecure.

Regarding your code, it looks okay. I don't know what's your issue unfortunately.

**Comment by Frenchcooc** [comment]
Closing this issue as I haven't heard back from you. Feel free to open a new issue if you still struggle.

And secure your instance ;)
