### ISSUE TITLE
Dynamic cloud id is not supported in Jira integration

### ISSUE THREAD

**Issue by guillaumemeyer** [Bearer/Pizzly#177]
As described in the [Jira OAuth documentation](https://developer.atlassian.com/cloud/jira/platform/oauth-2-authorization-code-grants-3lo-for-apps/#apicall), requests that use OAuth 2.0 (3LO) are made via api.atlassian.com (not https://your-domain.atlassian.net).
The URL should use the following structure: `Jira apps: https://api.atlassian.com/ex/jira/{cloudid}/{api}`
And an authenticated call to `https://api.atlassian.com/oauth/token/accessible-resources` should be made to retrieve the `cloudId`...

I see two options:
- Update Pizzly core to be able to include a prefetch call that would dynamically define the baseUrl from the definition
- Include a new proxy header such as `Pizzly-Base-Url` to define dynamically the base URL (that would be useful too for other platforms such as Salesforce)

**Comment by guillaumemeyer** [comment]
BTW, the `/oauth/token/accessible-resources` endpoint may return an array, and therefore it looks like there is no way to retrieve the site selected by the user during the scope approval process :-(
So my recommendation would be to include a new option in the proxy that would force the baseUrl property.

**Comment by Frenchcooc** [comment]
@guillaumemeyer I believe Pizzly should support forcing the `baseUrl`. It's something required as well to fully support other APIs, such as Google Sheets API, that sometimes have different baseUrl depending on the actions performed.

Are you interested in giving it a try?

**Comment by guillaumemeyer** [comment]
Count me in to try it asap @Frenchcooc .
I need this capability for both Jira Cloud and Salesforce.

**Comment by guillaumemeyer** [comment]
Any news?

**Comment by markmichon** [comment]
@guillaumemeyer Hey, you're earlier comment made it sound like you were working on it. Is that not the case?
