### ISSUE TITLE
Error during baseUrl interpolation using the Salesforce integration

### ISSUE THREAD

**Issue by guillaumemeyer** [Bearer/Pizzly#178]
Looks like the `${auth.tokenResponse.body.instance_url}` tag from the baseUrl property of the [Salesforce integration](https://github.com/Bearer/Pizzly/blob/master/integrations/salesforce.json) is never available and generates an exception during the interpolation.
A quick analysis shows that the `tokenResponse` property doesn't exist, but the `tokenResponseJSON` is there:
![image](https://user-images.githubusercontent.com/1385518/98749518-acf55280-2370-11eb-8578-eee7e8ca32fb.png)

**Comment by guillaumemeyer** [comment]
@Frenchcooc is it something that could be solved just by updating the configuration or does it needs a fix?

**Comment by Frenchcooc** [comment]
@guillaumemeyer looks like a glitch indeed. I'd recommend that you first give a try by updating the integration's configuration file to `tokenResponseJSON`. Did you try that already?

**Comment by guillaumemeyer** [comment]
I tried but the tokenResponseJSON is... wait for it... a stringified JSON, not an object :-( And through the interpolation, I can't use something like `${JSON.parse(auth.tokenResponseJSON).body.instance_url}` as far as I can remember...

**Comment by Frenchcooc** [comment]
Looks like a cat biting his tail to me... Will give it a try asap.

**Comment by guillaumemeyer** [comment]
Any news? Any way I can help?
