### ISSUE TITLE
Creating a new integration json doesn't add the API

### ISSUE THREAD

**Issue by RyukyuColin** [Bearer/Pizzly#179]
Documentation needs to be updated to include that any new /integrations JSON file must also be imported into /integrations/index.ts.

**Comment by markmichon** [comment]
Nice catch @RyukyuColin. The wiki has been updated to reflect the omission 👍

**Comment by moracabanas** [comment]
Sorry to reopen this issue, but in my case I got lost because my integration was not showing and I ended up here.
It seems this is not reflected on the README yet.
