### ISSUE TITLE
Payload not returned by connect

### ISSUE THREAD

**Issue by jawaxman** [Bearer/Pizzly#182]
When performing a connect (twitter, github, facebook), on success, the response contains only authId - payload is not present.

**Comment by markmichon** [comment]
Hi @jawaxman. Looks like there is an error in our docs for the js and node clients. They currently don't return the full auth payload. Sorry about that!

Instead, we recommend using either Proxy mode, where you use the client's get/post/etc methods to pass the authId to the endpoint of your choosing, and Pizzly handles the tokens. Alternately, you can use the [authentications API](https://github.com/Bearer/Pizzly/wiki/Reference-:-API#Authentications) to request the auth payload if you need access to the tokens directly.
