### ISSUE TITLE
Error with Spotify API - delete() request

### ISSUE THREAD

**Issue by markocalvocruz** [Bearer/Pizzly#186]
I'm trying to remove a song from an authenticated spotify user's playlist and for some reason, I get `Error 400 Missing Tracks`, even though I know the song is there and the playlist is correct

I am using [Pizzly from Bearer][1] to handle the API request

Any idea what could be causing this issue? This is the link to [Spotify's API Documentation][2]

This is an example output of `JSON.stringify(body)`

`{"tracks":[{"uri":"spotify:track:2fTdRdN73RgIgcUZN33dvt"}]}`

```javascript
   async removeSongsFromPlaylist(context, payload) {
        var tracks = payload[0]
        var playlistID = payload[1] || context.getters.user.favorites_playlist.id
        var authID = context.getters.spotifyAuthID
        var endpoint = `/playlists/${playlistID}/tracks`

        var uris = tracks.map(track => { return {uri: track.uri}})
        var body = {"tracks": uris}
        console.log(`URIS:`)
        console.log(body);
        console.log(`playlist: ${playlistID}`);
        return pizzly.integration("spotify").auth(authID).delete(endpoint, {
            body: JSON.stringify(body),
            headers: { "Content-Type": "application/json" }
            })
            .then(response => response.json())
            .then(responseJSON => {
                console.log("song successfully deleted")
                console.log(responseJSON)
            })
            .catch((err) => console.log(err))
        

    },

```

**Update:** I did make some progress with a very hacky solution

I took [Spotify's cURL example][3], converted it to fetch with this [link][4] and put that inside my function as so:

```javascript
        fetch(`https://api.spotify.com/v1/playlists/${playlistID}/tracks`, {
            body: "{\"tracks\":[{\"uri\":\"" + tracks[0].uri + "\"}]}",
            headers: {
                Accept: "application/json",
                Authorization: "Bearer ~accessTokenHiddenForPrivacy~",
                "Content-Type": "application/json"
            },
            method: "DELETE"
        })     
        .then(response => response.json())

```
Fortunately it worked! The problem is that after copy and pasting the `body` from `fetch` into the `pizzly` code,  it still shows "Missing Tracks". This makes me believe the issue is not with the body

  [1]: https://github.com/Bearer/Pizzly
  [2]: https://developer.spotify.com/documentation/web-api/reference/playlists/remove-tracks-playlist/
  [3]: https://developer.spotify.com/console/delete-playlist-tracks/?playlist_id=3cEYpjA9oz9GiPac4AsH4n&body=%7B%22tracks%22%3A%5B%7B%22uri%22%3A%22spotify%3Atrack%3A7MDKvOzNgAJ3KMCtaP2UOa%22%7D%5D%7D
  [4]: https://kigiri.github.io/fetch/

**Comment by markmichon** [comment]
Hey @markocalvocruz after some testing I was able to reproduce this. DELETE is working on some other spotify endpoints, so it isn't a blanket problem there. I'll look into it further, but I can't give you a timeline at the moment. 

For some context, the js client converts to fetch and sends it to Pizzly.  Then after handling the auth parts, Pizzly passes the request along as-is to Spotify. I suspect maybe there is some issue with the stringified data along the way, but unsure as of yet.

**Comment by markocalvocruz** [comment]
Hi Mark! Thank you so much for this reply! I was beginning to lose hope -
let me know how I might be able to assist



About Marko
<https://www.notion.so/Marko-Calvo-Cruz-cec9f36b992b472385cf2c11e23d2546>

**Comment by markocalvocruz** [comment]
Hey Mark - how are you. Are there any updates on this by any chance? Am
looking to launch my product soon and would be thrilled to be able to
include this feature. Am otherwise enjoying Pizzly and appreciate the work
your team does to support this service. . .

Thanks,
Marko
About Marko
<https://www.notion.so/Marko-Calvo-Cruz-cec9f36b992b472385cf2c11e23d2546>

**Comment by markmichon** [comment]
@markocalvocruz Unfortunately, like I mentioned there is no timeframe. We can't support every integration, and we encourage the community to contribute if they use an integration heavily. If it's really a pizzly-specific issue, you can try diving into the source itself and see if you can resolve the issue. I haven't seen similar issues in other integrations, and it appears that it is an edge case with that specific kind of deletion scenario and not the `delete` method of the client itself as other spotify deletion endpoints work fine. 

If anything changes I'll update this issue.
