### ISSUE TITLE
Delete Authentications with nodejs client

### ISSUE THREAD

**Issue by Nightbr** [Bearer/Pizzly#190]
Hey, thanks for this amazing OpenSource project! It helps me a lot to manage service integration :muscle: 

In my use case, I manage third-party service in my App and store the authId when the User has connected the service. But I would like to remove the Authentification with the nodejs client when the User delete (or disable) the service connection.

For example,

```TypeScript
import Pizzly from 'pizzly-node';

const pizzly = new Pizzly({
      host: 'http://localhost:8080',
      secretKey: 'mySecretKey',
    });

const gDrive = pizzly.integration('google-drive');

// Delete the Authentification object to clean it
gDrive.auth('my-auth-uuid').deleteAuthentification()
```

Thanks in advance for your help/support.

Best!

**Comment by markmichon** [comment]
Hey @Nightbr, thanks for being a part of the Pizzly community 💪!

Definitely a direction the node client could take. As-is, the node client is modeled after the JS client, so the feature-set comes from a mindset of limited access. Unfortunately this means none of the groundwork really exists for accessing those parts of the API, but it is definitely possible to build out. I'll flag this as an enhancement, and maybe someone from the community (or you) might be interested in picking it up.

You can directly access the API from within node as you would with any other http request. More details on the specific endpoint [at this page in the docs](https://github.com/Bearer/Pizzly/blob/master/docs/API.md#delete-an-authentication). You should be able to pass the appropriate headers and substitute the auth ID you received from the client to achieve the same thing.
