### ISSUE TITLE
Heroku Deploy Error

### ISSUE THREAD

**Issue by FractalHQ** [Bearer/Pizzly#192]
It seems the default Heroku config fails.  All I did was click the button, name the app, then click deploy.  I tried multiple times.  Any advice?

<img width="647" alt="Screenshot 2021-01-15 at 6 04 03 PM" src="https://user-images.githubusercontent.com/55504972/104786852-1f612500-575c-11eb-8673-0fe66bdb40ac.png">

**Comment by markmichon** [comment]
Hi @FractalHQ, very strange. On my first attempt I was able to reproduce the problem. Then I tried again, and it worked without an issue. I suspect there are some intermittent problems on Heroku's end when provisioning the db. Either way, give it another try and see if you still experience the issue.

**Comment by grey-cat-1908** [comment]
Yes, I have this error too. I tried to deploy 8 times, but I can't

**Comment by danielsvane** [comment]
Same issue, tried multiple times

**Comment by FractalHQ** [comment]
I've since tried again with no luck

**Comment by markmichon** [comment]
Looking into this, as I am now able to reproduce. Sadly, heroku wipes the release phase log when it fails so it is increasingly hard to debug. At first glance, it looks SSL related. They've also made some updates to their postgres offerings in January, which lines up with when this issue popped up.

For anyone else trying to debug, you can fork this repo then use `https://heroku.com/deploy?template=https://github.com/XXXXXX` with your repo to trigger a heroku click build.

**Comment by jgillard** [comment]
I just hit this issue, and have already pulled master with your latest commit mentioned above.

```
> pizzly@0.2.0 db:migrate
> knex --cwd dist/src/lib/database/config migrate:latest
Using environment: production
FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
error: no pg_hba.conf entry for host "54.171.30.207", user "XXX", database "XXX", SSL off
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:8:42)
    at Socket.emit (node:events:378:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at Socket.Readable.push (node:internal/streams/readable:227:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
npm ERR! code 1
npm ERR! path /app
npm ERR! command failed
npm ERR! command sh -c knex --cwd dist/src/lib/database/config migrate:latest
npm ERR! A complete log of this run can be found in:
npm ERR!     /app/.npm/_logs/2021-02-10T15_02_00_575Z-debug.log
```

**Comment by markmichon** [comment]
I had a few issues trying to reproduce @jgillard. Maybe heroku was having issues earlier? The 'deploy to heroku' button works thought:

<img width="670" alt="Screen Shot 2021-02-10 at 10 37 59 AM" src="https://user-images.githubusercontent.com/1649672/107555466-0f3a3b00-6b8c-11eb-8ea3-026fa2af6598.png">
