### ISSUE TITLE
Typeform <> Pizzly Callback URL Forbidden 

### ISSUE THREAD

**Issue by SamFrampton01** [Bearer/Pizzly#193]
I am trying to connect to Typeform integration using the Pizzly-JS library in React App. I've registered my app and added the callback URL provided in the pizzly dashboard following Typeform instructions. 

When I add connect function to button click the auth window opens with no problem but Typeform is having an issue with the Redirect URI I provided in the app configuration. Returning FORBIDDEN: Forbidden: redirect_uri is not allowed. After reading some threads other people have run into the same situation: https://github.com/Typeform/results-example/issues/7 

Can you provide a recommended workaround when using Pizzly library? Or provide a possible as to why might not be working.

Here is how I have configured Pizzly 

```
const pizzly = new Pizzly({
    host: 'dashboard.herokuapp.com/',
    publishableKey: process.env.PIZZLY_PUBLISHABLE_KEY,
  });
  const myAPI = pizzly.integration(`typeform`);
  console.log('api', myAPI);
  
   const connect = () => {
    myAPI
      .connect()
      .then(({ authId }) => {
        console.log('Sucessfully connected!', authId);
      })
      .catch(console.error);
  };
  
```

**Comment by markmichon** [comment]
Hi @SamFrampton01, make sure you are adding the callback URI that Pizzly mentions in the dashboard to the list of approved redirect URIs in typeform (see screenshot below). It follows the pattern like `https://YOUR-APP-NAME.herokuapp.com/auth/callback` 

<img width="420" alt="Screen Shot 2021-01-18 at 8 26 32 AM" src="https://user-images.githubusercontent.com/1649672/104940964-5192a280-5967-11eb-9f95-135fbfaee37d.png">

**Comment by SamFrampton01** [comment]
Hi @markmichon thanks for the quick response. I did as stated but have just refrehsed my token and re-updated the app and everything seems to work as expected now. 

Problem closed.

**Comment by markmichon** [comment]
Good to hear! Closing the issue.
