### ISSUE TITLE
Error connecting Zendesk Zopim 

### ISSUE THREAD

**Issue by SamFrampton01** [Bearer/Pizzly#194]
Hi, 

Great tool btw been playing around with it for a few days now and super impressed. 

I have a quick question on Zendesk Zopim Oauth credentials configuration requires the 'subdomain' query parameter to be encoded on URL parameters. 

I had a quick glance over zendesk-chat. config and I can see there is a subdomain param but I think it might be breaking the integration and not being passed as a parameter into base url. 

`   "authorizationParams": {
      "response_type": "token",
      "subdomain": "${connectParams.subdomain}"
    },`

**Comment by markmichon** [comment]
Hi @SamFrampton01, if you haven't resolved this, could you try using the connectParams during connection like this: 

```
pizzly.integration('zendesk-chat').connect({params:{subdomain:"<insert subdomain name here>"}})
```

**Comment by SamFrampton01** [comment]
Thanks, this is now resolved.
