### ISSUE TITLE
Unable to connect to shopify

### ISSUE THREAD

**Issue by Fastmind-inc** [Bearer/Pizzly#195]
I get an error saying 

We were unable to connect you. Make sure the application is configured correctly and/or contact the application owner to proceed further.

Error: MISSING_API_CONFIG_HEADER: The API's Authorization URL configuration requires the 'shop' query parameter to be passed when connecting.

 when I look at the shopify integration it does show it need the "connnectParams.shop" in the url, however I'm unsure of how to pass that.

**Comment by Fastmind-inc** [comment]
We were able to figure it out for anyone who might ran into the same issue.

`await pizzlyClient.integration('shopify').connect({params:{shop:"<insert show name here>"}})`

**Comment by markmichon** [comment]
Thanks for posting your solution @Fastmind-inc. The docs could definitely be more clear on how to handle connection params, so I'm adding it to the todo list 👍.

**Comment by timmyg** [comment]
@Fastmind-inc @markmichon 

hi all - do you have an example of actually using the shopify api to fetch data? I am getting a `422 (Unprocessable Entity)` when I try to `.get("/2021-01/orders.json?status=any")` with an authId I get back.  Not positive if that endpoint is structured correctly.

I created a codesandbox [here](https://codesandbox.io/s/pizzly-shopify-react-demo-yxnex?file=/src/App.js:1464-1503).

I tried out the github example and that worked (also included in the codesandbox). Any help or a point in the right direction would be super helpful! Thanks!

**Comment by markmichon** [comment]
@timmyg From a glance at your example when compared to fast's solution above, looks like you are setting the params on the integration method instead of on the connect method. Not sure if it will make a difference in this case, but could be the cause of your problems.

**Comment by timmyg** [comment]
@markmichon yea I did try that as well with no luck. I am going to try to pull down Pizzly and run it locally.

Really appreciate what you all have built and for the quick response.

**Comment by timmyg** [comment]
btw - i changed `shopify.json` to the below and it worked:

```
  "request": {
    "baseURL": "https://${auth.connectParams.shop}.myshopify.com/admin/api/",
```

I could then run:
```
await shopify
  .auth(authId)
  .get('/2021-01/shop.json')
  .then((response) => response.json())
  .then((json) => setDataShopify(json));
```

not sure if I am setting something up incorrectly in my code or it this was a bug. I can send a PR if you think it's a bug but not familiar enough with Pizzly to be sure.
