### ISSUE TITLE
Zoho CRM doesn't authenthicate correctly

### ISSUE THREAD

**Issue by Fastmind-inc** [Bearer/Pizzly#198]
the zoho crm doesn't authenticate correctly, it should be like https://github.com/Bearer/Pizzly/blob/master/integrations/zoho-invoices.json

the header authorization shows 

"Authorization": "Bearer ${auth.accessToken}",

like in zoho invoices it should be 

"Authorization": "Zoho-oauthtoken ${auth.accessToken}",

seems to also be a similar issue with zoho subscriptions

**Comment by Fastmind-inc** [comment]
The correct header is shown here  https://www.zoho.com/crm/developer/docs/api/v2/get-records.html

**Comment by cfabianski** [comment]
Hey @Fastmind-inc, thank you for reporting. 
Feel free to issue a Pull Request and we will review and get it merged as soon as possible.

**Comment by Fastmind-inc** [comment]
@cfabianski Went ahead and submitted the pull request
