### ISSUE TITLE
Where do I get the publishable keys

### ISSUE THREAD

**Issue by brianwachira** [Bearer/Pizzly#219]
I have gone through the documentation for more than 4 hours now. It is not clear where I can get the publishable keys. Where do I get the publishable keys?

**Comment by anuragphadke** [comment]
@brianwachira : are u self-hosting or on heroku/something else?
publishable keys are only needed when you are securing an instance.

Few docs for reference in case you missed them:
https://github.com/Bearer/Pizzly/blob/master/docs/getting-started.md
https://github.com/Bearer/Pizzly/blob/master/docs/securing-your-instance.md 
The publishable key is only valid once its explicitly setup as env variable.

**Comment by brianwachira** [comment]
I followed the instructions on  [https://github.com/Bearer/Pizzly#getting-started](https://github.com/Bearer/Pizzly#getting-started), hosted on heroku and I wanted to use my instance from a react application. On the code sandox example [https://codesandbox.io/s/pizzly-github-react-demo-rq78z](url), it shows that I need to have publishable keys and setup ID. Where am I to get them?

**Comment by markmichon** [comment]
@brianwachira If you're on heroku, you can set your keys in heroku interface under "Settings > Reveal Config Vars". You then need to create/set keys that match those listed in the "Securing your instance" doc that @anuragphadke posted.
![image](https://user-images.githubusercontent.com/1649672/114902098-592ce080-9dca-11eb-8d7e-3a3608d19350.png)

**Comment by brianwachira** [comment]
Thanks!
I have now seen where it explains on how to get secret key. It's on this link that @anuragphadke posted->  [https://github.com/Bearer/Pizzly/blob/master/docs/securing-your-instance.md#extra-options](url)
![image](https://user-images.githubusercontent.com/28436092/114906766-0d5a5580-9e23-11eb-9e59-06fc67ab1fdc.png)

I guess maybe the documentation could be improved so that the instructions are easily noticeable. I could help with that. 

I have another question,
Assuming I launched my pizzly instance on heroku while following  [ https://github.com/Bearer/Pizzly#getting-started,](URL) ,which sign up or register process should I follow on [https://bearer.sh](url), inorder to be able to reach [https://app.bearer.sh/settings/key](url) and get a secret key? 
![image](https://user-images.githubusercontent.com/28436092/114907618-f10ae880-9e23-11eb-8b3f-3a57fdd8c185.png)
The image above shows what Im getting when I follow the "Securing your instance" docs

**Comment by markmichon** [comment]
Ah sorry about the confusion, we need to change some things. Bearer's product is no longer focused on what is mentioned within Pizzly, so you won't be able to integrate it with Bearer (unless you're on a legacy account).

**Comment by brianwachira** [comment]
Alright. 
So that means I do not need a secret key, publishable key & setup ID in order to have it on my react app like in this example?
[https://codesandbox.io/s/pizzly-github-react-demo-rq78z?file=/src/App.js](url)

**Comment by markmichon** [comment]
If you want to securely access from a front-end app, you need the publishable key. Your react app, etc, will use the domain of your pizzly instance and the publishable key to authenticate.

**Comment by brianwachira** [comment]
This may sound like a noob question, but how do I generate a publishable key?
I guess publishable key is like a public key, right?

**Comment by markmichon** [comment]
There aren't any requirements for the publishable key, however for security it shouldn't match any secret keys or passwords that you use. Many people generate their key with a password generator.

**Comment by brianwachira** [comment]
> There aren't any requirements for the publishable key, however, for security, it shouldn't match any secret keys or passwords that you use. Many people generate their key with a password generator.

I wish I had known this earlier. I ended up creating an express server to handle OAuth. I guess the documentation could be improved?
