### ISSUE TITLE
Scripts May only close the windows opened by them Pizzly JS client

### ISSUE THREAD

**Issue by TanAidan** [Bearer/Pizzly#237]
I am using electron to create a desktop app. When I try to connect to pizzly through localhost on my browser, it works perfectly fine. When I use the electron app, I am able to authenticate but the window does not close due to the warning "Scripts May only close the windows opened by them"

**Comment by markmichon** [comment]
I believe electron uses a different system for handling message events from browser windows. Pizzly (the js client) has only really been tested in the browser. I personally haven't seen anyone use pizzly in electron, but it may require a custom client or some form of shim/polyfill from the electron community. The JS client should give some insight into the web technologies used for the message communication and might give you some idea of how to go about finding a solution.
