### ISSUE TITLE
Codesandbox examples in readme no longer working

### ISSUE THREAD

**Issue by johtso** [Bearer/Pizzly#256]
The examples no longer work:
[Pizzly + React](https://codesandbox.io/s/pizzly-github-react-demo-rq78z)
[Pizzly + Vue.js](https://codepen.io/frenchcooc/pen/RwrmXJw)

**Comment by MattRiddell** [comment]
I think there were some changes to free Heroku accounts lately?

Yeah:

[Heroku Announces End Of Free Services](https://www.i-programmer.info/news/84-database/15693-heroku-announces-end-of-free-services.html)
