### ISSUE TITLE
Add contributing guide

### ISSUE THREAD

**Issue by markmichon** [Bearer/Pizzly#51]
Add details on how to contribute including:
- `CONTRIBUTING.md` with details on dev environment, submitting PRs, etc
- Add issue and PR templates
- Add Contributors code of conduct (https://www.contributor-covenant.org/)

**Comment by Frenchcooc** [comment]
@markmichon  I'm closing this issue for now, as most items are now covered in the new README (except issue + PR templates but this might come later).
