### ISSUE TITLE
Provide a way to refresh a token whilst fetching it

### ISSUE THREAD

**Issue by didroe** [Bearer/Pizzly#60]
**Use case**: Using Pizzly for auth but not using the proxy

**Current situation**: There is an API `/:integrationId/authentications/:authenticationId` for fetching the auth info needed to make a request without the proxy. But this endpoint does not support refreshing tokens.

**Feature request**: Provide a separate endpoint (or parameter for the endpoint above) that supports refreshing the token (when required).

**Comment by Frenchcooc** [comment]
Great idea! Thanks for proposing this Dave ;) Out of curiosity, any particular reason you'd prefer to use Pizzly as an OAuth manager and not fully with the proxy?

**Comment by Frenchcooc** [comment]
Hi @didroe ! I'm closing this issue as it has been released in the latest version of Pizzly. Thanks again for proposing this!
