### ISSUE TITLE
Clearer instructions for "Securing your instance" when not using direnv

### ISSUE THREAD

**Issue by nabilfreeman** [Bearer/Pizzly#62]
Hi there!

I noticed that the instructions on "Securing your instance" (linked by default from Pizzly startup page) are geared towards using `.envrc` and `direnv`.

For people deploying to a PaaS like Heroku or Platform this isn't so relevant and might lead people to try to create those files in a locally cloned repo and commit them (which wouldn't work!)

The ideal would be to add a section such as...

If you are running Pizzly on a platform like Heroku or Platform.sh, you should configure the environment variables in the relevant section on the application dashboard.

This is usually a table like below:

| Environment Variable  | Value |
| ------------- | ------------- |
| DASHBOARD_USER  | example  |
| DASHBOARD_PASSWORD  | *******  |
| SECRET_KEY | ******* |
| PUBLISHABLE_KEY | ******* |
| BEARER_SECRET_KEY | sk_production_***** |

**Comment by Frenchcooc** [comment]
Thanks for the feedback Nabil. I've finally take some time to improve the instructions on "Securing your instance".

- PR #79 introduces a brand new page on the dashboard;
- and [the documentation has been improved](https://github.com/Bearer/Pizzly/wiki/Secure-your-instance), with link on how to proceed in Heroku.

This means that I'm closing this issue for now. Feel free to reopen it if ever you think more work should be done on that aspect.
