### ISSUE TITLE
Support for non-oauth APIs 

### ISSUE THREAD

**Issue by picsoung** [Bearer/Pizzly#74]
Hey Pizzly/Bearer team 👋 

Good job on open-sourcing Pizzly, looks really good!

There is one thing that I miss: is the support for APIs that don't use Auth for authentication.

Is that something you plan to add in the future? 

Thanks

**Comment by Frenchcooc** [comment]
Hi @picsoung! Thanks a lot for your feedback. We focus on OAuth based APIs today, as we believe it's where Pizzly can bring a lot of value. Adding more APIs and keep improving the developer experience are the main focus for now ;)
