### ISSUE TITLE
Wiki page is private

### ISSUE THREAD

**Issue by ulf1** [Bearer/Pizzly#87]
The page https://github.com/Bearer/Pizzly/wiki/Reference-:-Dashboard
says
![image](https://user-images.githubusercontent.com/8018044/91723237-bd809400-eb9b-11ea-857b-3e6c95a1dd0f.png)

**Comment by Frenchcooc** [comment]
Hi @ulf1! Thanks for reporting this. The wiki page was not created yet. This has been fixed ;)
