### ISSUE TITLE
How to generate SECRET_KEY and PUBLISHABLE_KEY

### ISSUE THREAD

**Issue by ulf1** [Bearer/Pizzly#88]
Hello, how can I generate `SECRET_KEY` and `PUBLISHABLE_KEY`?

**Comment by Frenchcooc** [comment]
Hi @ulf1. You can use a password manager to create unguessable string and save it in the manager. 

Another thing is to use a command line, such as `date +%s | sha256sum | base64 | head -c 32 ; echo` ([more examples](https://www.howtogeek.com/howto/30184/10-ways-to-generate-a-random-password-from-the-command-line/))
