### ISSUE TITLE
Make a POST/PUT

### ISSUE THREAD

**Issue by Devdre1909** [Bearer/Pizzly#90]
I am presently using Pizzly to integrate with Zoom, worked fine, it was almost magical. 
Now I need t make a post request to a zoom endpoint, how do I do this?

Tried this, where this.meetingRequest is the object I want to send

```
this.$pizzly
        .integration("zoom")
        .auth(this.$store.state.zoom.authId)
        .post(`https://api.zoom.us/v2/users/me/meetings`, this.meetingRequest)
        .then((response) => response.json())
        .then((data) => {
          console.log(data);
        })
        .catch(console.error);
```

**Comment by Frenchcooc** [comment]
Hi @Devdre1909! 

You're definitely on the right path. Pizzly does not support absolute URL for now - which is something I'd glad to change. For now, you need to provide the relative path based on [Zoom's configuration](https://github.com/Bearer/Pizzly/blob/230676db03b11c5b45b4d11faf44bf5386d04e84/integrations/zoom.json#L14). 

Here's your snippet changed accordingly:

```js
this.$pizzly
        .integration("zoom")
        .auth(this.$store.state.zoom.authId)
        .post(`/users/me/meetings`, this.meetingRequest) // I've changed this line
        .then((response) => response.json())
        .then((data) => {
          console.log(data);
        })
        .catch(console.error);
``` 

I haven't try this snippet on my side, but it should work! Let me know if it does (or not) ;)

**Comment by Devdre1909** [comment]
Thank you, especially for the quick reply

It didn't work, but I want back to the Wiki page, https://github.com/Bearer/Pizzly/wiki/Reference-:-Proxy#body, this worked for me.

```
this.$pizzly
        .integration("zoom")
        .auth(this.$store.state.zoom.authId)
        .post(`/users/me/meetings`, {
          body: JSON.stringify(this.meetingRequest),
          headers: { "Content-Type": "application/json" },
        })
        .then((response) => response.json())
        .then((data) => {
          console.log(data);
        })
        .catch(console.error);
```

My new code
