### ISSUE TITLE
Working without frontend :)

### ISSUE THREAD

**Issue by eusonlito** [Bearer/Pizzly#92]
I currently have a project connected with dropbox and google drive with oauth and all my connection is only using backend code.

1. My backend detect is user has a token on database related to service.
2. If token not exists, backend generate an auth url to oauth service (dropbox and google) with a redirect_url parameter to manage responses.
3. Backend check parameters (`state` and `code`) and generate an api token, as an usual on oauth services.
4. I have working all oauth process also with token refresh.

I'm coding a PHP API service to Pizzly based on your node service to release on finish.

* Can I do this process using Pizzly without frontend code?
* Can I get an Pizzly URL to send my users to be authenticated with oauth?
* Can Pizzly redirect to a redirect_url after that with the `authId`?

Once backend has a user `authId` I can connect my backend with Pizzly using my PHP service.

Thanks!

**Comment by Frenchcooc** [comment]
@eusonlito Pizzly works great for both backend and frontend applications. 

The only caveat with backend is that at some point you will need to prompt an authorization modal to the user. This needs to be managed by some frontend code (JS). But once you've an `authId` it's totally manageable from the backend.

* To prompt the authorization modal, here's [a lightweight snippet](https://github.com/Bearer/Pizzly/wiki/Examples#connect-to-an-api) and a long-format tutorial in [React](https://dev.to/frenchcooc/how-to-make-api-calls-in-react-g1e) or [Vue.js](https://dev.to/bearer/how-to-integrate-with-the-google-sheets-api-in-2-minutes-569o).
* To make API call from the backend, look at the [proxy](https://github.com/Bearer/Pizzly/wiki/Reference-:-Proxy) & [API](https://github.com/Bearer/Pizzly/wiki/Reference-:-API) references.

_PS: I might have not well understood what you're trying to achieve. If that's the case, I'm really sorry! Feel free to explain further or add a schema / diagram of the whole flow. That might be easier!_

**Comment by Frenchcooc** [comment]
@eusonlito closing this issue as I haven't heard back from you. Feel free to open a new one if you still need help
