### ISSUE TITLE
Discord integration?

### ISSUE THREAD

**Issue by alexpineda** [Bearer/Pizzly#98]
Just wondering if this is in the works.

**Comment by Frenchcooc** [comment]
Hi @alexpineda. Thanks for opening this issue. That would be great to support Discord!

New integration can be added with a JSON configuration file located within [./integrations](https://github.com/Bearer/Pizzly/tree/master/integrations). We are writing a guide on how to do that, to make it clearer. For now, feel free to look at other integrations configuration file and start a new PR with what you have done so far. We will all review it.
